name: Build

# read-write repo token
# access to secrets
on:
  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ '*.*.*' ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '.gitignore'
      - README.md
      - LICENSE
  workflow_call:

jobs:

  build:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        image: [novnc]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # This is the a separate action that sets up buildx runner for app
      - name: Set up Docker Buildx for ${{ matrix.image }}
        id: buildx
        uses: docker/setup-buildx-action@v2

      # So now you can use Actions' own caching!
      - name: Cache Docker layers for ${{ matrix.image }} image
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-${{ matrix.image }}
          key: ${{ runner.os }}-buildx-${{ matrix.image }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.image }}

      - name: Build Docker Image ${{ matrix.image }}
        uses: docker/build-push-action@v3 # Docs: https://github.com/docker/build-push-action#usage
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          load: true
          target: ${{ matrix.image }}
          cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.image }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ matrix.image }}-new,mode=max

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-${{ matrix.image }}
          mv /tmp/.buildx-cache-${{ matrix.image }}-new /tmp/.buildx-cache-${{ matrix.image }}

  push:
    if: ${{ github.event.pull_request.draft == false && (github.ref_type == 'tag' || github.ref_name == 'master') }}
    strategy:
      matrix:
        image: [novnc]
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # This is the a separate action that sets up buildx runner for app
      - name: Set up Docker Buildx for ${{ matrix.image }}
        id: buildx
        uses: docker/setup-buildx-action@v2

      # So now you can use Actions' own caching!
      - name: Cache Docker layers for ${{ matrix.image }} image
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-${{ matrix.image }}
          key: ${{ runner.os }}-buildx-${{ matrix.image }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.image }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image ${{ matrix.image }} to latest
        if:  ${{ github.ref_name == 'master' }}
        uses: docker/build-push-action@v2 # Docs: https://github.com/docker/build-push-action#usage
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          target: ${{ matrix.image }}
          cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.image }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ matrix.image }}-new,mode=max
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest

      - name: Build and push Docker image ${{ matrix.image }} to ${{ github.event.number }}
        if:  ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v2 # Docs: https://github.com/docker/build-push-action#usage
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          target: ${{ matrix.image }}
          cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.image }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ matrix.image }}-new,mode=max
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.event.number }}

      - name: Build and Push Docker Image ${{ matrix.image }} to release
        if:  ${{ github.ref_type == 'tag' }}
        uses: docker/build-push-action@v2 # Docs: https://github.com/docker/build-push-action#usage
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          target: ${{ matrix.image }}
          cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.image }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ matrix.image }}-new,mode=max
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.ref_name }}

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        if:  ${{ github.ref_type == 'tag' || github.ref_name == 'master' }}
        run: |
          rm -rf /tmp/.buildx-cache-${{ matrix.image }}
          mv /tmp/.buildx-cache-${{ matrix.image }}-new /tmp/.buildx-cache-${{ matrix.image }}
